name: Build Vault Canister
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Install candid-extractor
        run: cargo install candid-extractor
      - name: Checkout dfx-setup
        uses: actions/checkout@v2
      - name: Install dfx
        uses: dfinity/setup-dfx@main
      - name: Confirm successfull dfx install
        run: dfx --version
      - name: start dfx 
        run: dfx start --background --clean
      - name: create all canisters
        run: dfx canister create --all
      - name: build all canisters
        run: dfx build
      - name: upload shared vault wasm
        uses: actions/upload-artifact@v4
        with:
          name: shared_vault_canister_backend_wasm
          path: target/wasm32-unknown-unknown/release/shared_vault_canister_backend.wasm
          compression-level: 0
      - name: upload shared vault did
        uses: actions/upload-artifact@v4
        with:
          name: shared_vault_canister_backend_did
          path: src/shared-vault-canister-backend/shared-vault-canister-backend.did
          compression-level: 0
      - name: upload vault wasm
        uses: actions/upload-artifact@v4
        with:
          name: vault_canister_backend_wasm
          path: target/wasm32-unknown-unknown/release/vault_canister_backend.wasm
          compression-level: 0
      - name: upload vault did
        uses: actions/upload-artifact@v4
        with:
          name: vault_canister_backend_did
          path: src/vault-canister-backend/vault-canister-backend.did
          compression-level: 0